"use client";

import { motion } from "framer-motion"; // Importing the motion library
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/1SVIMb24Wq3
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Judson } from 'next/font/google'
import { Chivo } from 'next/font/google'

judson({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button";

export function Pricing() {
  return (
    <motion.section
      className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800"
      initial={{ opacity: 0, y: 50 }} // Initial animation properties
      animate={{ opacity: 1, y: 0 }} // Animation properties on load
      exit={{ opacity: 0, y: -50 }} // Animation properties on exit
    >
      <div className="container grid gap-12 px-4 md:px-6">
        <div className="flex flex-col items-center justify-center space-y-4 text-center">
          <div className="space-y-2">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl text-gray-900 dark:text-gray-50">
              Pricing
            </h2>
            <p className="max-w-[700px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              Choose the plan that fits your needs. We have options for students
              as well as course creators.
            </p>
          </div>
        </div>
        <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
          <motion.div
            className="flex flex-col justify-between rounded-lg border border-gray-200 bg-white p-6 shadow-sm transition-all hover:shadow-md dark:border-gray-800 dark:bg-gray-950"
            whileHover={{ scale: 1.05 }} // Animation on hover
          >
            <div className="space-y-4">
              <h3 className="text-2xl font-bold text-gray-900 dark:text-gray-50">
                Starter (Free)
              </h3>
              <p className="text-gray-500 dark:text-gray-400">
                Perfect for students who want to learn and explore.
              </p>
              <ul className="space-y-2">
                <li className="flex items-center gap-2">
                  <CheckIcon className="w-5 h-5 text-green-700" />
                  Access to all free courses
                </li>
                <li className="flex items-center gap-2">
                  <CheckIcon className="w-5 h-5 text-green-700" />
                  Community support
                </li>
                <li className="flex items-center gap-2">
                  <XIcon className="w-5 h-5 text-red-500" />
                  Premium Courses
                </li>
                <li className="flex items-center gap-2">
                  <XIcon className="w-5 h-5 text-red-500" />
                  Personalized AI support
                </li>
                <li className="flex items-center gap-2">
                  <XIcon className="w-5 h-5 text-red-500" />
                  Certifications
                </li>
              </ul>
              <div className="flex items-end gap-1">
                <span className="text-4xl font-bold">$0</span>
                <span className="text-gray-500 dark:text-gray-400">
                  /per month
                </span>
              </div>
            </div>
            <Button
              className="mt-6 w-full bg-gray-900 text-white hover:bg-gray-800 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-200"
              variant="outline"
            >
              Get Started
            </Button>
          </motion.div>
          <motion.div
            className="flex flex-col justify-between rounded-lg border-2 border-green-500  bg-white p-6 shadow-sm transition-all hover:shadow-md dark:border-gray-800 dark:bg-gray-950 relative"
            whileHover={{ scale: 1.05 }} // Animation on hover
          >
            <div className="absolute top-0 right-0 bg-green-500 text-white px-3 py-1 rounded-bl-lg font-semibold text-sm">
              Most Popular
            </div>
            <div className="space-y-4">
              <h3 className="text-2xl font-bold text-gray-900 dark:text-gray-50">
                Students
              </h3>
              <p className="text-gray-500 dark:text-gray-400">
                For students who need more features and support.
              </p>
              <ul className="space-y-2">
                <li className="flex items-center gap-2">
                  <CheckIcon className="w-5 h-5 text-green-700" />
                  Access to all Free courses
                </li>

                <li className="flex items-center gap-2">
                  <CheckIcon className="w-5 h-5 text-green-700" />
                  Community support
                </li>
                <li className="flex items-center gap-2">
                  <CheckIcon className="w-5 h-5 text-green-700" />
                  Premium Courses
                </li>
                <li className="flex items-center gap-2">
                  <CheckIcon className="w-5 h-5 text-green-700" />
                  Personalized AI support
                </li>
                <li className="flex items-center gap-2">
                  <CheckIcon className="w-5 h-5 text-green-700" />
                  Certifications
                </li>
              </ul>
              <div className="flex items-end gap-1">
                <span className="text-4xl font-bold">$4.99</span>
                <span className="text-gray-500 dark:text-gray-400">
                  /per month
                </span>
              </div>
            </div>
            <Button className="mt-6 w-full text-white border-1 border-green-600  shadow-lg ">
              Start Learning
            </Button>
          </motion.div>
          <motion.div
            className="flex flex-col justify-between rounded-lg border border-gray-200 bg-white p-6 shadow-sm transition-all hover:shadow-md dark:border-gray-800 dark:bg-gray-950"
            whileHover={{ scale: 1.05 }} // Animation on hover
          >
            <div className="space-y-4">
              <h3 className="text-2xl font-bold text-gray-900 dark:text-gray-50">
                Developer
              </h3>
              <p className="text-gray-500 dark:text-gray-400">
                For developers and course creators who wants to create their own
                courses.
              </p>
              <ul className="space-y-2">
                <li className="flex items-center gap-2">
                  <CheckIcon className="w-5 h-5 text-green-700" />
                  Access to all courses
                </li>
                <li className="flex items-center gap-2">
                  <CheckIcon className="w-5 h-5 text-green-700" />
                  Create your own Courses
                </li>
                <li className="flex items-center gap-2">
                  <CheckIcon className="w-5 h-5 text-green-700" />
                  Customer Support
                </li>
                <li className="flex items-center gap-2">
                  <CheckIcon className="w-5 h-5 text-green-700" />
                  Certifications
                </li>
              </ul>
              <div className="flex items-end gap-1">
                <span className="text-4xl font-bold">$14.99</span>
                <span className="text-gray-500 dark:text-gray-400">
                  /per month
                </span>
              </div>
            </div>
            <Button
              className="mt-6 w-full bg-gray-900 text-white hover:bg-gray-800 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-200"
              variant="outline"
            >
              Start Building
            </Button>
          </motion.div>
        </div>
      </div>
    </motion.section>
  );
}

function CheckIcon(props: any) {
  return (
    <motion.svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      initial={{ opacity: 0 }} // Initial animation properties
      animate={{ opacity: 1 }} // Animation properties on load
    >
      <path d="M20 6 9 17l-5-5" />
    </motion.svg>
  );
}

function XIcon(props: any) {
  return (
    <motion.svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      initial={{ opacity: 0 }} // Initial animation properties
      animate={{ opacity: 1 }} // Animation properties on load
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </motion.svg>
  );
}
